name: Keep Backend Alive by Attempting User Registration

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  registration:
    runs-on: ubuntu-latest
    steps:
      - name: Attempt to register an existing user
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"email":"${{ secrets.USER_EMAIL }}", "firstName":"Test", "lastName":"User", "password":"${{ secrets.USER_PASSWORD }}"}' \
          ${{ secrets.API_ENDPOINT }}
